# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'nfl-mock-draft' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nfl-mock-draft
  pod 'Firebase/Core'

  target 'nfl-mock-draftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nfl-mock-draftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
